---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-sort-keys"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.13.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        exclude: .github/workflows/pipeline.yml

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shellcheck
        files: (tests/run-.*|tests/update)$

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-1
    hooks:
      - id: shfmt
        files: (tests/run-.*|tests/update)$

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.33.0
    hooks:
      - id: markdownlint
